# 项目启动端口
server:
  address: :8888
  # debug模式
  model: debug
  # release模式
  # model:release

db:
  dialects: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  db: voting-ranking
  charset: utf8mb4
  # 最大空闲数
  maxIdle: 50
  # 最大连接数
  maxOpen: 150



# log日志配置
log:
  path: ./log
  name: sys
  # 输出到控制台
  # model: console
  # 输出到文件
  model: file
